
// This file has been generated by the GUI designer. Do not modify.
public partial class MainWindow
{
	private global::Gtk.VBox vbox4;
	private global::Gtk.Entry recuadro;
	private global::Gtk.Table table4;
	private global::Gtk.Button B1;
	private global::Gtk.Button B2;
	private global::Gtk.Button B3;
	private global::Gtk.Button B4;
	private global::Gtk.Button B5;
	private global::Gtk.Button B6;
	private global::Gtk.Button B7;
	private global::Gtk.Button B8;
	private global::Gtk.Button B9;
	private global::Gtk.Button BDIVIDIR;
	private global::Gtk.Button BIGUAL;
	private global::Gtk.Button BMAS;
	private global::Gtk.Button BMENOS;
	private global::Gtk.Button BMULTI;
	private global::Gtk.Button BPUNTO;
	private global::Gtk.Button BZ;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.recuadro = new global::Gtk.Entry ();
		this.recuadro.CanFocus = true;
		this.recuadro.Name = "recuadro";
		this.recuadro.IsEditable = true;
		this.recuadro.InvisibleChar = '•';
		this.vbox4.Add (this.recuadro);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.recuadro]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.table4 = new global::Gtk.Table (((uint)(4)), ((uint)(4)), false);
		this.table4.Name = "table4";
		this.table4.RowSpacing = ((uint)(6));
		this.table4.ColumnSpacing = ((uint)(6));
		// Container child table4.Gtk.Table+TableChild
		this.B1 = new global::Gtk.Button ();
		this.B1.CanFocus = true;
		this.B1.Name = "B1";
		this.B1.UseUnderline = true;
		this.B1.Label = global::Mono.Unix.Catalog.GetString ("1");
		this.table4.Add (this.B1);
		// Container child table4.Gtk.Table+TableChild
		this.B2 = new global::Gtk.Button ();
		this.B2.CanFocus = true;
		this.B2.Name = "B2";
		this.B2.UseUnderline = true;
		this.B2.Label = global::Mono.Unix.Catalog.GetString ("2");
		this.table4.Add (this.B2);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table4 [this.B2]));
		w3.LeftAttach = ((uint)(1));
		w3.RightAttach = ((uint)(2));
		// Container child table4.Gtk.Table+TableChild
		this.B3 = new global::Gtk.Button ();
		this.B3.CanFocus = true;
		this.B3.Name = "B3";
		this.B3.UseUnderline = true;
		this.B3.Label = global::Mono.Unix.Catalog.GetString ("3");
		this.table4.Add (this.B3);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table4 [this.B3]));
		w4.LeftAttach = ((uint)(2));
		w4.RightAttach = ((uint)(3));
		// Container child table4.Gtk.Table+TableChild
		this.B4 = new global::Gtk.Button ();
		this.B4.CanFocus = true;
		this.B4.Name = "B4";
		this.B4.UseUnderline = true;
		this.B4.Label = global::Mono.Unix.Catalog.GetString ("4");
		this.table4.Add (this.B4);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table4 [this.B4]));
		w5.TopAttach = ((uint)(1));
		w5.BottomAttach = ((uint)(2));
		w5.XOptions = ((global::Gtk.AttachOptions)(4));
		w5.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.B5 = new global::Gtk.Button ();
		this.B5.CanFocus = true;
		this.B5.Name = "B5";
		this.B5.UseUnderline = true;
		this.B5.Label = global::Mono.Unix.Catalog.GetString ("5");
		this.table4.Add (this.B5);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table4 [this.B5]));
		w6.TopAttach = ((uint)(1));
		w6.BottomAttach = ((uint)(2));
		w6.LeftAttach = ((uint)(1));
		w6.RightAttach = ((uint)(2));
		w6.XOptions = ((global::Gtk.AttachOptions)(4));
		w6.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.B6 = new global::Gtk.Button ();
		this.B6.CanFocus = true;
		this.B6.Name = "B6";
		this.B6.UseUnderline = true;
		this.B6.Label = global::Mono.Unix.Catalog.GetString ("6");
		this.table4.Add (this.B6);
		global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table4 [this.B6]));
		w7.TopAttach = ((uint)(1));
		w7.BottomAttach = ((uint)(2));
		w7.LeftAttach = ((uint)(2));
		w7.RightAttach = ((uint)(3));
		w7.XOptions = ((global::Gtk.AttachOptions)(4));
		w7.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.B7 = new global::Gtk.Button ();
		this.B7.CanFocus = true;
		this.B7.Name = "B7";
		this.B7.UseUnderline = true;
		this.B7.Label = global::Mono.Unix.Catalog.GetString ("7");
		this.table4.Add (this.B7);
		global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table4 [this.B7]));
		w8.TopAttach = ((uint)(2));
		w8.BottomAttach = ((uint)(3));
		w8.XOptions = ((global::Gtk.AttachOptions)(4));
		w8.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.B8 = new global::Gtk.Button ();
		this.B8.CanFocus = true;
		this.B8.Name = "B8";
		this.B8.UseUnderline = true;
		this.B8.Label = global::Mono.Unix.Catalog.GetString ("8");
		this.table4.Add (this.B8);
		global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table4 [this.B8]));
		w9.TopAttach = ((uint)(2));
		w9.BottomAttach = ((uint)(3));
		w9.LeftAttach = ((uint)(1));
		w9.RightAttach = ((uint)(2));
		w9.XOptions = ((global::Gtk.AttachOptions)(4));
		w9.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.B9 = new global::Gtk.Button ();
		this.B9.CanFocus = true;
		this.B9.Name = "B9";
		this.B9.UseUnderline = true;
		this.B9.Label = global::Mono.Unix.Catalog.GetString ("9");
		this.table4.Add (this.B9);
		global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table4 [this.B9]));
		w10.TopAttach = ((uint)(2));
		w10.BottomAttach = ((uint)(3));
		w10.LeftAttach = ((uint)(2));
		w10.RightAttach = ((uint)(3));
		w10.XOptions = ((global::Gtk.AttachOptions)(4));
		w10.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.BDIVIDIR = new global::Gtk.Button ();
		this.BDIVIDIR.CanFocus = true;
		this.BDIVIDIR.Name = "BDIVIDIR";
		this.BDIVIDIR.UseUnderline = true;
		this.BDIVIDIR.Label = global::Mono.Unix.Catalog.GetString ("/");
		this.table4.Add (this.BDIVIDIR);
		global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table4 [this.BDIVIDIR]));
		w11.TopAttach = ((uint)(3));
		w11.BottomAttach = ((uint)(4));
		w11.LeftAttach = ((uint)(3));
		w11.RightAttach = ((uint)(4));
		w11.XOptions = ((global::Gtk.AttachOptions)(4));
		w11.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.BIGUAL = new global::Gtk.Button ();
		this.BIGUAL.CanFocus = true;
		this.BIGUAL.Name = "BIGUAL";
		this.BIGUAL.UseUnderline = true;
		this.BIGUAL.Label = global::Mono.Unix.Catalog.GetString ("=");
		this.table4.Add (this.BIGUAL);
		global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table4 [this.BIGUAL]));
		w12.TopAttach = ((uint)(3));
		w12.BottomAttach = ((uint)(4));
		w12.LeftAttach = ((uint)(1));
		w12.RightAttach = ((uint)(2));
		w12.XOptions = ((global::Gtk.AttachOptions)(4));
		w12.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.BMAS = new global::Gtk.Button ();
		this.BMAS.CanFocus = true;
		this.BMAS.Name = "BMAS";
		this.BMAS.UseUnderline = true;
		this.BMAS.BorderWidth = ((uint)(3));
		this.BMAS.Label = global::Mono.Unix.Catalog.GetString ("+");
		this.table4.Add (this.BMAS);
		global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table4 [this.BMAS]));
		w13.LeftAttach = ((uint)(3));
		w13.RightAttach = ((uint)(4));
		// Container child table4.Gtk.Table+TableChild
		this.BMENOS = new global::Gtk.Button ();
		this.BMENOS.CanFocus = true;
		this.BMENOS.Name = "BMENOS";
		this.BMENOS.UseUnderline = true;
		this.BMENOS.Label = global::Mono.Unix.Catalog.GetString ("-");
		this.table4.Add (this.BMENOS);
		global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table4 [this.BMENOS]));
		w14.TopAttach = ((uint)(1));
		w14.BottomAttach = ((uint)(2));
		w14.LeftAttach = ((uint)(3));
		w14.RightAttach = ((uint)(4));
		w14.XOptions = ((global::Gtk.AttachOptions)(4));
		w14.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.BMULTI = new global::Gtk.Button ();
		this.BMULTI.CanFocus = true;
		this.BMULTI.Name = "BMULTI";
		this.BMULTI.UseUnderline = true;
		this.BMULTI.Label = global::Mono.Unix.Catalog.GetString ("X");
		this.table4.Add (this.BMULTI);
		global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table4 [this.BMULTI]));
		w15.TopAttach = ((uint)(2));
		w15.BottomAttach = ((uint)(3));
		w15.LeftAttach = ((uint)(3));
		w15.RightAttach = ((uint)(4));
		w15.XOptions = ((global::Gtk.AttachOptions)(4));
		w15.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.BPUNTO = new global::Gtk.Button ();
		this.BPUNTO.CanFocus = true;
		this.BPUNTO.Name = "BPUNTO";
		this.BPUNTO.UseUnderline = true;
		this.BPUNTO.Label = global::Mono.Unix.Catalog.GetString (".");
		this.table4.Add (this.BPUNTO);
		global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table4 [this.BPUNTO]));
		w16.TopAttach = ((uint)(3));
		w16.BottomAttach = ((uint)(4));
		w16.LeftAttach = ((uint)(2));
		w16.RightAttach = ((uint)(3));
		w16.XOptions = ((global::Gtk.AttachOptions)(4));
		w16.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.BZ = new global::Gtk.Button ();
		this.BZ.CanFocus = true;
		this.BZ.Name = "BZ";
		this.BZ.UseUnderline = true;
		this.BZ.Label = global::Mono.Unix.Catalog.GetString ("0");
		this.table4.Add (this.BZ);
		global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table4 [this.BZ]));
		w17.TopAttach = ((uint)(3));
		w17.BottomAttach = ((uint)(4));
		w17.XOptions = ((global::Gtk.AttachOptions)(4));
		w17.YOptions = ((global::Gtk.AttachOptions)(4));
		this.vbox4.Add (this.table4);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.table4]));
		w18.Position = 1;
		w18.Expand = false;
		w18.Fill = false;
		this.Add (this.vbox4);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 363;
		this.DefaultHeight = 183;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.BZ.Clicked += new global::System.EventHandler (this.cero_clicked);
		this.BPUNTO.Clicked += new global::System.EventHandler (this.punto_clicked);
		this.BMULTI.Clicked += new global::System.EventHandler (this.Operation_clicked);
		this.BMENOS.Clicked += new global::System.EventHandler (this.Operation_clicked);
		this.BMAS.Clicked += new global::System.EventHandler (this.Operation_clicked);
		this.BIGUAL.Clicked += new global::System.EventHandler (this.igual_clicked);
		this.BDIVIDIR.Clicked += new global::System.EventHandler (this.Operation_clicked);
		this.B9.Clicked += new global::System.EventHandler (this.B1_clicked);
		this.B8.Clicked += new global::System.EventHandler (this.B1_clicked);
		this.B7.Clicked += new global::System.EventHandler (this.B1_clicked);
		this.B6.Clicked += new global::System.EventHandler (this.B1_clicked);
		this.B5.Clicked += new global::System.EventHandler (this.B1_clicked);
		this.B4.Clicked += new global::System.EventHandler (this.B1_clicked);
		this.B3.Clicked += new global::System.EventHandler (this.B1_clicked);
		this.B2.Clicked += new global::System.EventHandler (this.B1_clicked);
		this.B1.Clicked += new global::System.EventHandler (this.B1_clicked);
	}
}
